### ISSUE TITLE
SVM model 

### ISSUE THREAD

**Issue by juancorzamar93** [mumido/Grupo12_Proyecto_FraudBuster#1]
Vamos a implementar una variante del SVM conocida como Linear SVM (Support Vector Machine), entrenada mediante descenso de gradiente estocástico (SGD)

Comparación:

SVM Clásico: Utiliza optimización cuadrática, adecuado para conjuntos de datos pequeños a medianos, pero se vuelve ineficiente para grandes volúmenes de datos.

SGDClassifier con 'hinge': Utiliza descenso de gradiente estocástico, adecuado para conjuntos de datos grandes, proporciona una aproximación del SVM lineal con mucho menos costo computacional.

**Comment by juancorzamar93** [comment]
Falta hacer predicción del modelo con hiperparámetros

**Comment by mumido** [comment]
Etapa final del proyecto concluída
